postgres:
  image: postgres:latest

django-tenants-test:
  build: .
  links:
    - postgres
  volumes:
    - .:/code:z
  command: ./run_tests_in_docker.sh
  environment:
    DATABASE_HOST: postgres
  ports:
    - "8080:8080"
